# Generated by Django 2.1.4 on 2019-01-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trippin_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='memories',
        ),
    ]
